name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please search existing issues to avoid duplicates.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the contributing guidelines
          required: true
        - label: This issue is related to the GitOps Express Cluster project
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0]
        - Kubernetes Version: [e.g. 1.27.0]
        - ArgoCD Version: [e.g. 2.8.0]
        - Tekton Version: [e.g. 0.50.0]
        - Cloud Provider: [e.g. AWS EKS, GKE, AKS, local]
        - Browser (if applicable): [e.g. Chrome 114.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please provide any relevant logs or error messages
      placeholder: |
        ```
        kubectl logs <pod-name> -n <namespace>
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks important functionality
        - Critical - Severe issue affecting production
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which components are affected by this bug?
      options:
        - label: ArgoCD
        - label: Tekton Pipelines
        - label: Kustomize
        - label: Kubernetes Manifests
        - label: Monitoring (Prometheus/Loki)
        - label: Canary Deployments
        - label: HPA/Autoscaling
        - label: Security/RBAC
        - label: Documentation
        - label: CI/CD 