apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nodejs-app-canary

namespace: nodejs-app

resources:
  - ../../base
  - canary-deployment.yaml
  - canary-service.yaml
  - traffic-split.yaml

commonLabels:
  deployment-type: canary
  
patchesStrategicMerge:
  - ingress-canary-patch.yaml

images:
  - name: nodejs-app
    newTag: canary

configMapGenerator:
  - name: canary-config
    behavior: merge
    literals:
      - DEPLOYMENT_TYPE=canary
      - CANARY_ENABLED=true
      - TRAFFIC_PERCENTAGE=10

namePrefix: canary- 