apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  labels:
    app: nodejs-app
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguie2/gitops-express-cluster.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    managedFieldsManagers:
    - kube-controller-manager
  info:
  - name: 'Documentation'
    value: 'https://github.com/nguie2/gitops-express-cluster/blob/main/README.md'
  - name: 'Monitoring'
    value: 'https://grafana.example.com/d/nodejs-app'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-canary
  namespace: argocd
  labels:
    app: nodejs-app
    environment: canary
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguie2/gitops-express-cluster.git
    targetRevision: main
    path: k8s/overlays/canary
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-app
  syncPolicy:
    automated:
      prune: false  # Manual canary management
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 5
  info:
  - name: 'Canary Status'
    value: '10% traffic split'
  - name: 'Rollback Command'
    value: 'argocd app sync nodejs-app-canary --revision HEAD~1' 