apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue-exporter
  labels:
    app: redis-queue-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-queue-exporter
  template:
    metadata:
      labels:
        app: redis-queue-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.45.0
        ports:
        - containerPort: 9121
          name: metrics
        env:
        - name: REDIS_ADDR
          value: "redis://redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: "json"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: queue-length-calculator
        image: alpine/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache redis
          while true; do
            QUEUE_LENGTH=$(redis-cli -h redis-service -p 6379 -a $REDIS_PASSWORD llen job_queue)
            echo "# HELP redis_queue_length Redis queue length"
            echo "# TYPE redis_queue_length gauge"
            echo "redis_queue_length{queue_name=\"job_queue\",redis_instance=\"main\"} $QUEUE_LENGTH"
            sleep 30
          done
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true

---
apiVersion: v1
kind: Service
metadata:
  name: redis-queue-exporter-service
  labels:
    app: redis-queue-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 9121
    targetPort: 9121
    protocol: TCP
    name: metrics
  selector:
    app: redis-queue-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-queue-exporter
  labels:
    app: redis-queue-exporter
spec:
  selector:
    matchLabels:
      app: redis-queue-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  labels:
    app: redis
type: Opaque
stringData:
  password: "your-redis-password-here" 