apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nodejs-app-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - rbac.yaml

commonLabels:
  app: nodejs-app
  version: v1.0.0
  managed-by: kustomize

namespace: nodejs-app

images:
  - name: nodejs-app
    newTag: latest

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis-service:6379
    files:
      - configs/app.json

secretGenerator:
  - name: app-secrets
    type: Opaque
    literals:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/nodejs_app
      - JWT_SECRET=your-jwt-secret-here
      - REDIS_PASSWORD=your-redis-password 