apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodejs-app-role
  labels:
    app: nodejs-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodejs-app-rolebinding
  labels:
    app: nodejs-app
subjects:
- kind: ServiceAccount
  name: nodejs-app-sa
  namespace: nodejs-app
roleRef:
  kind: Role
  name: nodejs-app-role
  apiGroup: rbac.authorization.k8s.io 